// 40+ NPC dialogue lines. Pulled at random by <DialogueBox />.
// Keep the voice flat, canned, and self-aware. No exclamation-point enthusiasm.

export const DIALOGUE_LINES: string[] = [
  'I used to be an adventurer like you. Then I took a paycheck to the knee.',
  'Nice weather we’re having. I would not know. I do not go outside.',
  'Have you heard of the high elves? Me neither. I just say that.',
  'Welcome to the shop. We sell shirts.',
  'I have been standing here since 2024.',
  'My programming does not allow me to offer discounts. [10% OFF: CODE NPC10]',
  'You have clicked on me 0 times. Please stop.',
  'This is a safe zone. No PvP. Mostly no PvE either.',
  'Would you like to hear a rumor? The rumor is that this hoodie exists.',
  'I have three lines of dialogue. This is one of them.',
  'Loading personality... personality not found. Shipping default fit instead.',
  'I respawn here every morning. So do you, technically.',
  'Talk to me again for the same information.',
  'Quest available: Buy a shirt. Reward: A shirt.',
  'I am legally distinct from a background character. Ask my lawyer, who is also me.',
  'You seem lost. Have you tried the shop tab? It is right there. I am pointing. You cannot see me point.',
  'Some say I whisper the same six words to everyone who walks by. Some say I said that.',
  'Fun fact: I am rendered even when you are not looking at me. Unsettling, right?',
  'I do not have a name. I have a slug: npc-outfitters.',
  'You could be the main character. Statistically, you are not.',
  'This dialogue box has no skip button. That is intentional.',
  'I once glitched through a wall. HR is still discussing it.',
  'Buy something. Or don’t. I will be here either way. I have nowhere else to be.',
  'The devs gave me a walking animation but nowhere to walk.',
  'Achievement unlocked: Read An NPC’s Dialogue For No Reason.',
  'I am contractually obligated to mention free shipping over $50.',
  'There is no lore reason I am selling clothes. There is a business reason.',
  'You have been standing here just as long as I have. Curious.',
  'I do not remember you. I never will. Come back tomorrow and I still won’t.',
  'Somewhere, a main character is having a very different day than you.',
  'This item was made in a factory. So was every item you own. At least we said it out loud.',
  'I ran the numbers. Blending in is 100% effective at being unnoticed.',
  'Warning: this shop contains no lore, only merchandise.',
  'I have low-poly hands. I still managed to fold these hoodies.',
  'You can pet the cat. There is no cat. There is a hoodie shaped like disappointment, sort of.',
  'Insert coin to continue. We do not accept coins. We accept cards.',
  'I was going to say something profound. Then the shipment came in.',
  'Every outfit here has been focus-tested on zero focus groups.',
  'This is not a cutscene. You can leave at any time. Please don’t.',
  'The game does not remember your choices. Neither does our returns department, please keep your receipt.',
  'I have seen things. Mostly this shop. I have seen this shop a lot.',
  'You weren’t supposed to see this.',
  'Reload the page. I will say something slightly different. It is the whole gimmick.',
  'Somewhere a designer is very proud of this dialogue box. That designer is also me.',
  'Rare drop incoming. Or not. Depends on the algorithm’s mood.',
  'I am a background character with a storefront. Life comes at you weird.',
];
