// 20+ fake-but-labeled-fake NPC reviews for the ticker.

export interface FakeReview {
  quote: string;
  author: string;
}

export const FAKE_REVIEWS: FakeReview[] = [
  { quote: 'It’s a shirt.', author: 'Verified NPC' },
  { quote: 'I wore it and no one noticed me. 5 stars.', author: 'Anonymous' },
  { quote: 'Blended in at three separate family gatherings.', author: 'Background Character #402' },
  { quote: 'My friends said “huh, new shirt?” Mission failed successfully.', author: 'Verified NPC' },
  { quote: 'I have said the same six words to every customer since I bought this.', author: 'Shopkeeper NPC' },
  { quote: 'Fits like it was never going to be memorable. Correct.', author: 'Anonymous' },
  { quote: 'Durability 100/100. Personality -3. Worth it.', author: 'Verified NPC' },
  { quote: 'I stood in the same spot for a week to test it. Held up.', author: 'Quest Giver, Unemployed' },
  { quote: 'Someone asked where I got it. I forgot the answer immediately, in character.', author: 'Verified NPC' },
  { quote: 'The gray hoodie matched my personality: none.', author: 'Anonymous' },
  { quote: 'I respawned in it. 10/10 spawn fit.', author: 'Verified NPC' },
  { quote: 'Not a single main character interaction while wearing this. Perfect.', author: 'Extra #1187' },
  { quote: 'The tag says “Made Honestly.” I appreciated the lack of lying.', author: 'Anonymous' },
  { quote: 'Bought it ironically. Wear it sincerely. Standard outcome.', author: 'Verified NPC' },
  { quote: 'I clipped through a wall wearing this. Unrelated to the shirt, still 5 stars.', author: 'Anonymous' },
  { quote: 'The stat block undersold the comfort by at least 2 points.', author: 'Verified NPC' },
  { quote: 'It arrived. That’s really the whole review.', author: 'Anonymous' },
  { quote: 'I am contractually a background character. This is now my uniform.', author: 'Extra #204' },
  { quote: 'Zero individuality gained, exactly as advertised on the box.', author: 'Verified NPC' },
  { quote: 'My npc dialogue improved 12% after wearing this. Unconfirmed causation.', author: 'Anonymous' },
  { quote: 'The socks made my feet disappear into the crowd. Great socks.', author: 'Verified NPC' },
  { quote: 'I have never been the main character. This hoodie respects that.', author: 'Anonymous' },
  { quote: 'Shipping was honest about being slow. I respected that more than the shirt.', author: 'Verified NPC' },
  { quote: 'It is gray. It is exactly as gray as promised.', author: 'Quality Control NPC' },
];

export const REVIEWS_DISCLAIMER =
  'Reviews generated by NPCs. NPCs cannot lie. Or can they. No.';
